title: C:\\Welcome
author: Milo-Hwejae
email: hwejae94@korea.ac.kr
description: > # this means to ignore newlines until "show_exerpts:"
  Milo-Hwejae's Blog, <br />
  About data driven security

paginate: 1
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: #https://twitter.com/bitbrain_
      icon: twitter-square
      color: cyan
    #- url: https://bitbrain.itch.io
    #  icon: itch-io
    #  color: red
    - url: https://github.com/Milo-HweJae
      icon: github-square
      color: purple

  show_author: true

  animation_speed: 50

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
#avatar_source: github
#github_username: Milo-Hwejae
